language: cpp
compiler: gcc

os: linux

sudo: required
dist: precise
group: legacy

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential libtool autotools-dev autoconf pkg-config libssl-dev libcrypto++-dev
  - sudo apt-get install -y libboost-all-dev
  - sudo add-apt-repository -y ppa:silknetwork/silknetwork
  - sudo apt-get update -y && sudo apt-get install -y libdb4.8-dev libdb4.8++-dev
  - sudo apt-get install -y libminiupnpc-dev
  - sudo apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libcrypto++-dev
  - sudo apt-get install -y libqrencode-dev libevent-dev

script:
  - ./autogen.sh && ./configure --with-gui=qt5 && make

deploy:
  provider: releases
  file: "silk-qt"
  skip_cleanup: true
  on:
    tags: true
